### ISSUE TITLE
Mission.jsx mobile responsiveness

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/rishi-website#72]
change src/components/home/mission to flex-col instead of flex row on small screens so it doesn't look crushed like this 
<img width="876" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/90938120/015d9525-e738-4f9e-a8e4-f3cc560f4ae8">

use tailwind breakpoints

https://tailwindcss.com/docs/responsive-design

**Comment by twang0323** [comment]
<img width="1113" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/122486013/6fb6baf5-2970-44a4-a48e-9554f5b6e354">
<img width="628" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/122486013/3e626560-ddc9-488c-ae21-0f7f9644159e">
