### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/rishi-website#9]
src/components/Footer.jsx

* example footer https://github.com/acm-ucr/hlg-website/blob/dev/src/components/Footer.jsx
* [react icons](https://acm-ucr.github.io/docusaurus/docs/react-icons/usage) for social icons
* design https://www.figma.com/file/Er8O1kH9UNeOnndCS885bT/RISHI?type=design&node-id=0-1&mode=design&t=Q5tKROKv3OwftGWM-0

<img width="1280" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/90938120/e7d8b24f-e2a1-414a-8800-ad12935c670b">

how it looks on a page 
<img width="1280" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/90938120/d705214d-0ce1-4dde-8bed-e5c66642b060">

**Comment by twang0323** [comment]
<img width="1077" alt="image" src="https://github.com/acm-ucr/rishi-website/assets/122486013/80d72ddb-3be8-4d8c-a282-d355c5525028">
